apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: workspace-sandbox-template
  namespace: default
spec:
  podTemplate:
    spec:
      runtimeClassName: kata-qemu     
      containers:
      - name: agent-debian-workspace
        image: debian-workspace-sandbox:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: "/"
            port: 8888
          initialDelaySeconds: 0
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: "/"
            port: 8888
          initialDelaySeconds: 2
          periodSeconds: 10
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "8Gi"
      restartPolicy: OnFailure